export const GITHUB_API = "https://api.github.com"

export const defaultGitHubRepository: FetchRepo = {
    id: 0,
    node_id: "",
    name: "",
    full_name: "",
    private: false,
    owner: {
        login: "",
        id: 0,
        node_id: "",
        avatar_url: "",
        gravatar_id: "",
        url: "",
        html_url: "",
        followers_url: "",
        following_url: "",
        gists_url: "",
        starred_url: "",
        subscriptions_url: "",
        organizations_url: "",
        repos_url: "",
        events_url: "",
        received_events_url: "",
        type: "User",
        user_view_type: "public",
        site_admin: false,
    },
    html_url: "",
    description: "",
    fork: false,
    url: "",
    forks_url: "",
    keys_url: "",
    collaborators_url: "",
    teams_url: "",
    hooks_url: "",
    issue_events_url: "",
    events_url: "",
    assignees_url: "",
    branches_url: "",
    tags_url: "",
    blobs_url: "",
    git_tags_url: "",
    git_refs_url: "",
    trees_url: "",
    statuses_url: "",
    languages_url: "",
    stargazers_url: "",
    contributors_url: "",
    subscribers_url: "",
    subscription_url: "",
    commits_url: "",
    git_commits_url: "",
    comments_url: "",
    issue_comment_url: "",
    contents_url: "",
    compare_url: "",
    merges_url: "",
    archive_url: "",
    downloads_url: "",
    issues_url: "",
    pulls_url: "",
    milestones_url: "",
    notifications_url: "",
    labels_url: "",
    releases_url: "",
    deployments_url: "",
    created_at: "",
    updated_at: "",
    pushed_at: "",
    git_url: "",
    ssh_url: "",
    clone_url: "",
    svn_url: "",
    homepage: "",
    size: 0,
    stargazers_count: 0,
    watchers_count: 0,
    language: "",
    has_issues: false,
    has_projects: false,
    has_downloads: false,
    has_wiki: false,
    has_pages: false,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: false,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: "public",
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: "main",
    temp_clone_token: null,
    network_count: 0,
    subscribers_count: 0,
    createdAt: null
};


export const colorMap = {
    "Java": "#fc0335",
    "C": "#8c939c",
    "C++": "#292dab",
    "Python": "#2b07f2",
    "JavaScript": "#e3d514",
    "TypeScript": "#1677f5",
    "Ruby": "#9c1a21",
    "C#": "#563382",
    "CSS": "#0a8ca6",
    "HTML": "#ed7e15",
    "Markdown" : "#0a5c0a",
    "Jupyter Notebook" : "#ed4d2d"
}


export const defaultIssue: IssuesType = {
    url: "",
    id: 0,
    title: "Default Title",
    html_url: "",
    user: {
      login: "default_user",
      id: 0,
      avatar_url: "",
      html_url: "",
      type: "User",
    },
    state: "open",
  };

  export const defaultPopularRepoPayload : PopularRepoPayloadType = {
    language : '',
    topic : '',
    startCount : 10000
  }

  export const defaultUserJWTPayload: UserJWTPayload = {
    id: 0,
    name: '',
    email: '',
    bookMarkedNumbers: []
};

export const defaultUserFetched: UserFetched = {
  id: 0, 
  name: "", 
  email: "", 
  password: "", 
  isVerified: false, 
  isAdmin: false, 
  verifyPasswordToken: "",
  verfiyPasswordTokenExpiry: null, 
  verifyToken: "", 
  verifyTokenExpiry: null, 
  bookMarkedNumbers: [] 
};


const defaultGitHubUser: GitHubUser = {
  login: "abir499-ban",
  id: 169090270,
  node_id: "U_kgDOChQc3g",
  avatar_url: "https://avatars.githubusercontent.com/u/169090270?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/abir499-ban",
  html_url: "https://github.com/abir499-ban",
  followers_url: "https://api.github.com/users/abir499-ban/followers",
  following_url: "https://api.github.com/users/abir499-ban/following{/other_user}",
  gists_url: "https://api.github.com/users/abir499-ban/gists{/gist_id}",
  starred_url: "https://api.github.com/users/abir499-ban/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/abir499-ban/subscriptions",
  organizations_url: "https://api.github.com/users/abir499-ban/orgs",
  repos_url: "https://api.github.com/users/abir499-ban/repos",
  events_url: "https://api.github.com/users/abir499-ban/events{/privacy}",
  received_events_url: "https://api.github.com/users/abir499-ban/received_events",
  type: "User",
  user_view_type: "public",
  site_admin: false,
  contributions: 47,
};


  
  
